[general]
bars = 10
framerate = 60
sensitivity = 100
autosens = 1
noise_reduction = 0.5

[input]
method = pulse
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 7
